#!/usr/bin/env bash
# Author
author="Philip Mello <@Microsoft>"
# Version
version="1.0"
# License
license="MIT"
# Date
current_date=$(date +'%b %d, %Y')
# GitHub
github='https://github.com/PhilipMello/cloudflare/'

echo "
                  _   _                  
   |              | | | |                 
 __|   _  _    ,  | | | |  __,   ,_    _    # Script     : Cloudflare DNS Script Automation
/  |  / |/ |  / \_|/  |/  /  |  /  |  |/    # Description: Create DNS entries for Cloudflare
\_/|_/  |  |_/ \/ |__/|__/\_/|_/   |_/|__/  # Version    : $version
                  |\                        # Date       : $current_date
                  |/                        # Author     : $author
# License    : $license
# Github     : $github
# --------------------------------------------------------------
# How to use: Execute ./dnsflare
# Examples:
# Manual: ./dnsflare -h OR ./dnsflare --h OR ./dnsflare --help
# --------------------------------------------------------------
"
WHITE=""
BLUE="\033[97;104m"
YELLOW="\033[97;103m"
CYAN="\033[97;106m"
MAGENTA="\033[97;45m"
GREEN="\033[97;102m"
RED="\033[97;41m"
ENDCOLOR="\e[0m"

# Read sitename
echo "Type your site name, (Ex: mysite.com)"
read sitename

# Read Subdomain
echo "Would you like to add Subdomain ? Enter (y, n)"
read option

if [[ $option == [Yy] ]]; then
    echo "Enter your subdomain (Ex: dev)"
    read subdomain
elif [[ $option == [Nn] ]]; then
    echo "No Sundomain added"
else
    echo "Invalid input."
fi

# Read server IP address (IPv4)
echo "Type your Server IP (IPv4)"
read serverip

# Read DKIM
echo "Paste your DKIM here (Type ENTER to skip)"
read dkim

cloudflare="
;;
;; Domain:     $sitename.
;; Created:   $current_date
;;

;; A Records
$sitename.	1	IN	A	$serverip ; Root domain pointing to Server IPv4. (DNS Only)
mail.$sitename.	1	IN	A	$serverip
www.$sitename.	1	IN	A	$serverip ; WWW.Domain pointing to Server IPv4. (DNS Only)
www.mail.$sitename.	1	IN	A	$serverip

;; CNAME Records
$subdmain.	1	IN	CNAME	$sitename. ; Subdomain

;; MX Records
$sitename.	1	IN	MX	10 $sitename.

;; PTR Records
$serverip.$sitename.	1	IN	PTR	$sitename. ; rDNS

;; TXT Records
$sitename.	1	IN	TXT	v=spf1 a mx -all
default._domainkey.$sitename.	1	IN	TXT	$dkim "'ADD DKIM HERE'" ; DKIM record
_dmarc.$sitename.	1	IN	TXT	v=DMARC1;p=quarantine;rua=mailto:admin@$sitename

"

cloudflareurl="https://dash.cloudflare.com/"

# File
file="$sitename.txt"
echo "$cloudflare" > $file
message="
# --------------------------------------------------------------
# DNS Records Created Succesfully for CloudFlare
# File            :"$sitename.txt"
# Date            :$current_date
# DNS Provider    :CloudFlare
# CloudFlare URL  :$cloudflareurl
# --------------------------------------------------------------
"
echo "$message"

exit 0